jQuery(document).ajaxError(function(event,request,settings){if(request.responseText.indexOf("<!DOCTYPE")>-1)location.reload()});jQuery(document).ready(function(){$(document).ajaxStart(function(){if(!PSBeng.data.ajaxBlock)return;$.unblockUI();$.blockUI({css:{border:"none",padding:"15px",backgroundColor:"#000","-webkit-border-radius":"10px","-moz-border-radius":"10px",opacity:.5,color:"#fff"}})});$(document).ajaxStop(function(){$.unblockUI()});PSBeng.init()});
var PSBeng={data:{lastDataRequest:{},last_seo_power:0,ajaxBlock:true,last_alert_text:""},genAllItems:{data:{status:0,currentEntity:0,entities:["product","category","brand","info","standard"]},init:function(){$(".gen_all_items").click(function(){PSBeng.genAllItems.preparegenerate()})},preparegenerate:function(){PSBeng.genAllItems.data.status=1;$(".tab-pane.active").find("."+PSBeng.genAllItems.data.entities[PSBeng.genAllItems.data.currentEntity]+"-preparegenerate").click()},generate:function(){PSBeng.genAllItems.data.status=
1;var $button=$(".tab-pane.active").find("."+PSBeng.genAllItems.data.entities[PSBeng.genAllItems.data.currentEntity]+"-generate");$button.before('<input name="gen_mode_allitems" class="gen_mode_allitems" type="text" value="1">');$button.click();PSBeng.genAllItems.data.currentEntity+=1;if(PSBeng.genAllItems.data.entities.length-1==PSBeng.genAllItems.data.currentEntity)PSBeng.genAllItems.end()},end:function(){$(".tab-pane.active").find(".status").removeClass("status-on").removeClass("status-off").addClass("status-on");
PSBeng.genAllItems.data.currentEntity=0;PSBeng.genAllItems.data.status=0;$(".gen_mode_allitems").remove()}},progress:{show:function(){var progress=$("#progress_bar_container").html();progress+='<div class="gen_status_bar" style="margin-top:-30px; "><span>Start process!</span></br></div>';$.unblockUI();$.blockUI({message:progress,css:{border:"none",padding:"0px",width:"50%",top:"200px",left:"25%",backgroundColor:"transparent","-webkit-border-radius":"10px","-moz-border-radius":"10px",opacity:1,color:"#fff"}});
PSBeng.progress.update(0,"")},update:function(val,text,last_pack_status){var val=val>100?100:val;if(text)PSBeng.progress.refreshText(text,last_pack_status);$(".blockUI #progress_bar .ui-progress").animateProgress(val)},remove:function(){$.unblockUI()},refreshText:function(text,last_pack_status){var $g_s_b=$(".gen_status_bar");var text="<p>"+text+"</p>";var $g_s_b_p=$(".gen_status_bar>p");if($g_s_b_p.length>5)$g_s_b_p.first().remove();if(last_pack_status){$g_s_b_p.last().find("span").remove();var l_p_s=
last_pack_status?last_pack_status:"";$g_s_b_p.last().html($g_s_b_p.last().html()+l_p_s)}$g_s_b.append(text)}},showAlert:function(text,time,cursor){$.unblockUI();var time=time?time:4E3;var block_ui={fadeIn:700,fadeOut:700,timeout:time,showOverlay:false,centerY:false,css:{width:"350px",top:"100px",left:"","font-size":"120%",right:"30px",border:"2px solid #FF0808",padding:"15px",backgroundColor:"#fff","-webkit-border-radius":"5px","-moz-border-radius":"5px",opacity:.85,color:"#FF0808",cursor:cursor?
cursor:"wait","z-index":9999999}};setTimeout(function(){$.blockUI($.extend({message:text},block_ui))},100)},showError:function(data){$.unblockUI();var block_ui={fadeIn:700,fadeOut:700,timeout:4E3,showOverlay:false,centerY:false,css:{width:"350px",top:"100px",left:"","font-size":"120%",right:"30px",border:"2px solid #fff",padding:"15px",backgroundColor:"red","-webkit-border-radius":"5px","-moz-border-radius":"5px",opacity:.7,color:"#fff"}};var text='<p style="text-align:left;font-size:20px;">';$.each(data,
function(k,v){text+='<span style="font-size:18px;">Error:</span> '+v+"</br>"});text+="</p>";setTimeout(function(){$.blockUI($.extend({message:text},block_ui))},200)},init:function(){$("*[data-toggle=tooltip]").tooltip({html:true});PSBeng.modalLoadInit();PSBeng.setRadioControllValue();$(".accordion-inner .close").click(function(){$(this).parents(".accordion-group").find(".collapse").collapse("hide")});$(".grider").grider({countRow:true,countRowAdd:true});var $modal_header=$(".grider").parents(".modal").find(".modal-header");
$modal_header.append($(".grider caption"));PSBeng.patternAddValue.init();$(".on_off").iphoneStyle({width:50,height:70,onChange:function(self){if(!$(self).parents(".controls").find("input.on_off").hasClass("noAlert")){PSBeng.data.ajaxBlock=false;PSBeng.showAlert("Saving...")}PSBeng.action($(self).parents(".controls").find("input[data-action]"))}});PSBeng.handler();PSBeng.genAllItems.init()},handler:function(){$(".btn").click(function(){PSBeng.action($(this))})},patternAddValue:{data:{active_param:""},
init:function(){$(".seo_button_pattern").click(function(){if(!$(this).attr("data-addValPattern"))$(this).parents("fieldset").find(".active .seo_input_pattern").insertAtCaret($(this).text());else{$self=$(this);var body_html=PSBeng.patternAddValue.getHtmlForModal($self);$modal=$("#modal-setAdditionPatternValue");$modal.find("H4 span").html('"'+$self.attr("data-paramName")+'"');$modal.find(".modal-body").html(body_html);$modal.modal("show");$("*[data-toggle=tooltip]").tooltip({html:true});PSBeng.patternAddValue.data.active_param=
$self}});$(".insert-param-with-addValue").click(function(){PSBeng.patternAddValue.writeToTemplate($(this))})},writeToTemplate:function($button){var $parameter=PSBeng.patternAddValue.data.active_param;var $inputs=$button.closest("#modal-setAdditionPatternValue").find("input");var changed=false;var addValPattern=$parameter.attr("data-addValPattern");var addValue=PSBeng.patternAddValue.getAddValFromParam($parameter);var av_names=addValue.name;var av_values=addValue.value;$inputs.each(function(){var name=
$(this).attr("name");var def_val=av_values[$.inArray(name,av_names)];var input_val=$(this).val();addValPattern=addValPattern.replace(name,input_val);if(input_val!=def_val)changed=true});setTimeout(function(){if(changed){var param_addVavue=" "+$.trim($parameter.text())+addValPattern+" ";$parameter.parents("fieldset").find(".active .seo_input_pattern").insertAtCaret(param_addVavue)}else $parameter.parents("fieldset").find(".active .seo_input_pattern").insertAtCaret($parameter.text())},500)},getAddValFromParam:function($parameter){var addValue=
eval("("+$self.attr("data-addValue")+")");return addValue},getHtmlForModal:function($parameter){var form_element={"int":'<input name="%s" class="span2" value="%s" min="%s" max="%s" type="number" data-toggle="tooltip" data-original-title="Must be between %s to %s" data-placement="right">',"str":'<input name="%s" class="span2" value="%s" minlength="%s" maxlength="%s" type="text" data-toggle="tooltip" data-temp-min="%s" data-original-title="Can be max %s character" data-placement="right">'};var form_fieldset=
'<tr><td><fieldset><div class="control-group"><label class="control-label">%s</label><div class="controls">%s</div></div></fieldset></td></tr>';var form_container_start='<form class="form-horizontal"><table class="table table-condensed no-border"><tbody>';var form_container_end="</tbody></table></form>";var addValue=PSBeng.patternAddValue.getAddValFromParam($parameter);var av_names=addValue.name;var av_values=addValue.value;var paramName=$parameter.attr("data-paramName").toLowerCase();paramName=paramName==
"category name"?"categories":paramName;$.each(av_values,function(i,value){if(PSBdat.MD_PatternAddVal[av_names[i]]["text"]=="Text before every ")paramName=paramName=="example products"?"product":paramName;var text=PSBdat.MD_PatternAddVal[av_names[i]]["text"]+paramName;var type=PSBdat.MD_PatternAddVal[av_names[i]]["type"];var range=PSBdat.MD_PatternAddVal[av_names[i]]["range"];var html_element=sprintf(form_element[type],av_names[i],value,range[0],range[1],range[0],range[1]);var html_fieldset=sprintf(form_fieldset,
text,html_element);form_container_start=form_container_start+html_fieldset});var form_container=form_container_start+form_container_end;return form_container}},modalLoadInit:function(){$("[data-toggle=modal]").not(".modal_ajax_activate").click(function(event){event.preventDefault();var url=$(this).attr("href");if(url.indexOf("#")!==0)$.get(url,function(data){$('<div class="modal hide fade modal-absolute width_95 ajax_modal">'+data+"</div>").modal().on("hidden",function(){$("[data-toggle=modal]").removeData();
$(this).remove();$(".modal-backdrop").remove()});setTimeout(function(){PSBeng.modalLoadInit();$modal_grider=$(".ajax_modal .grider");$modal_grider.grider({countRow:true,countRowAdd:true});$(".ajax_modal .btn").click(function(){PSBeng.action($(this))})},500)}).success(function(){$("input:text:visible:first").focus()})}).addClass("modal_ajax_activate")},action:function($btn){var action=$btn.attr("data-action");if(typeof action==="undefined"||action===false)return;$(".ckeditor textarea").each(function(){var $textarea=
$(this);$textarea.val(CKEDITOR.instances[$textarea.attr("id")].getData())});var afterAction=$btn.attr("data-afterAction")?$btn.attr("data-afterAction"):action;if($btn.attr("data-jsaction")){eval($btn.attr("data-jsaction"));return}if($btn.attr("data-jsbeforeaction"))eval($btn.attr("data-jsbeforeaction"));var data_entity=$btn.attr("data-entity")?$btn.attr("data-entity"):"";var formData=getFormData();if(formData){if(data_entity)$.extend(formData,{"metaData[entity]":data_entity});PSBeng.data.lastDataRequest=
formData}formData=PSBeng.data.lastDataRequest;$.extend(formData,{"metaData[action]":action});PSBeng.ajax(formData,"json","PSBeng."+afterAction);function getFormData(){var formData=false;if($btn.attr("data-data")&&$btn.attr("data-data")!="")formData={"data":$btn.attr("data-data")};else if($btn.attr("data-scope")&&$btn.attr("data-scope")!=""){var $scope="";formData={};eval("$scope = $btn"+$btn.attr("data-scope")+";");var scope_data=$scope.serializeArray();for(index=0;index<scope_data.length;++index){var data=
scope_data[index];eval('$.extend(formData, {"'+data.name+'" : data.value});')}}return formData}},testGenerate:function(data){$("#modal-testGenerate").find("p.seo_text").html('<table class="result_test_generet table">'+data.seo_text+"</table>");$("#modal-testGenerate").modal("show")},prepareGenerate:function(data){PSBeng.data.curr_pack=0;$("#modal-prepareGenerate").find("p.total_text").html(data.total_text);$("#modal-prepareGenerate").find("p.confirm_text").html(data.confirm_text);PSBeng.data.total_pack=
(100/(data.total_genPack+2)).toFixed(2);if(!PSBeng.genAllItems.data.status)$("#modal-prepareGenerate").modal("show");else PSBeng.genAllItems.generate()},processGenerate:function(data,pack_status){var curr_pack=PSBeng.data.curr_pack;var progress=(new Number(PSBeng.data.total_pack*(curr_pack+1))).toFixed(2);var status={"success":'<span class="label label-success"> ...done!</span>',"error":'<span class="label label-warning"> ...Error</span>'};var preloader='<span class="preload"><img src="'+PSBdat.HTTP_SERVER+
'view/stylesheet/psm_library/images/gen_process__.gif"></img></span>';var text_line="generated pack "+curr_pack+" "+preloader;if(pack_status){var pack_status=status[pack_status];if(pack_status=="error")text_line="re-"+text_line}PSBeng.progress.update(progress,text_line,pack_status);if(data.process=="go"){formData=PSBeng.data.lastDataRequest;$.extend(formData,{"metaData[action]":"processGenerate","metaData[pack]":curr_pack});PSBeng.data.curr_pack++;ajaxGenPack(formData)}else if(data.process=="stop"){if(PSBeng.genAllItems.data.status){PSBeng.genAllItems.preparegenerate();
return}formData=PSBeng.data.lastDataRequest;$.extend(formData,{"metaData[action]":"endGenerate"});PSBeng.ajax(formData,"json","PSBeng.endGenerate")}function ajaxGenPack(data){var url=PSBdat.url.ajax;$.ajax({url:url,dataType:"json",type:"POST",data:data,success:function(data){pack_status="success";PSBeng.processGenerate(data,pack_status)},statusCode:{404:function(){pack_status="error";PSBeng.data.curr_pack--;PSBeng.processGenerate({process:"go"},pack_status)},502:function(){pack_status="error";PSBeng.data.curr_pack--;
PSBeng.processGenerate({process:"go"},pack_status)}}})}},setRadioControllValue:function(){$(".radioControllValue a").on("click",function(){$(this).closest(".radioControllValue").find("input[type=hidden]").val($(this).attr("data-condition"))})},endGenerate:function(data){setTimeout(function(){PSBeng.progress.update(100,"All done!",'<span class="label label-success"> ...done!</span>')},1E3);PSBeng.data.ajaxBlock=true;if(data.alert_text)PSBeng.showAlert(JSON.stringify(data.alert_text));if(isset(data.index_files))PSBeng.updateTestArea(data.index_files);
PSBeng.changeStatus(data)},updateTestArea:function(index_files){if(index_files){$(".test_area div.store_link").html(index_files);$(".test_area").show("slow")}else $(".test_area").hide("slow")},changeStatus:function(data){var category=data.entityData.category.name;var entity=data.entityData.entity.name;var internal_entity=data.entityData.internal_entity.name;var category_status=data.genStatus;if(entity=="all")var $statusEntity=$(".tab-pane.active").find("div[id^=TDKT_"+category+"]").find(".status");
else var $statusEntity=$(".tab-pane.active").find("div[id^=TDKT_"+category+"-"+entity+"]").find(".status");setStatus($statusEntity,data.genStatus);var $statusEntities=$("#seo_generator_"+category).find(".status");category_status=false;$statusEntities.each(function(){if($(this).hasClass("status-on"))category_status=true});var $statusCategory=$("a[href=#seo_generator_"+category+"]").find(".status");setStatus($statusCategory,category_status);function setStatus($el_status,status){$el_status.removeClass("status-off").removeClass("status-on");
if(status)$el_status.addClass("status-on");else $el_status.addClass("status-off")}},prepareClearGenerate:function(data){$("#modal-prepareClearGenerate").find("p.total_text").html(data.total_text);$("#modal-prepareClearGenerate").find("p.confirm_text").html(data.confirm_text);$("#modal-prepareClearGenerate").modal("show")},startClearGenerate:function(data){if(data.alert_text)PSBeng.showAlert(JSON.stringify(data.alert_text));PSBeng.changeStatus(data);if(isset(data.index_files))PSBeng.updateTestArea(data.index_files)},
repeatAction:function(data){PSBeng.afterAction(data)},afterAction:function(data){if(!data)return;if(data.error)PSBeng.showError(data.error);if(data.alert)PSBeng.showAlert(JSON.stringify(data.alert));if(data.status)PSBeng.changeStatus(data);if(isset(data.index_files))PSBeng.updateTestArea(data.index_files)},refreshReviewTable:function(data){$(".modal .close").click();setTimeout(function(){$("."+data.data+"_open").click()},200)},ajax:function(data,dataType,func,url,timeOutForAlert){if(!url||url=="")var url=
PSBdat.url.ajax;if(!dataType||dataType=="")var dataType="text";$.ajax({url:url,dataType:dataType,type:"POST",data:data,success:function(data){if(func&&func!="")eval(func+"(data)");else if(dataType=="text")PSBeng.setHTML(data,timeOutForAlert);else PSBeng.afterAction(data)},statusCode:{404:function(){alert("Error 404")},502:function(){alert("Error 502")}}})},setHTML:function(html,timeOut){$(".content").html(html);PSBeng.init();introStart(document,introfunction);if(PSBeng.data.last_alert_text){var timeOut=
timeOut?timeOut:800;setTimeout(function(){PSBeng.showAlert(PSBeng.data.last_alert_text);PSBeng.data.last_alert_text=""},timeOut)}},save:function(data){}};
jQuery.fn.extend({insertAtCaret:function(myValue){return this.each(function(i){if(document.selection){this.focus();var sel=document.selection.createRange();sel.text=myValue;this.focus()}else if(this.selectionStart||this.selectionStart=="0"){var startPos=this.selectionStart;var endPos=this.selectionEnd;var scrollTop=this.scrollTop;this.value=this.value.substring(0,startPos)+myValue+this.value.substring(endPos,this.value.length);this.focus();this.selectionStart=startPos+myValue.length;this.selectionEnd=
startPos+myValue.length;this.scrollTop=scrollTop}else{this.value+=myValue;this.focus()}})}});function sprintf(format){for(var i=1;i<arguments.length;i++)format=format.replace(/%s/,arguments[i]);return format}
(function($){$.fn.animateProgress=function(progress,callback){return this.each(function(){$(this).animate({width:progress+"%"},{duration:200,easing:"swing",step:function(progress){var labelEl=$(".ui-label",this),valueEl=$(".value",labelEl);if(Math.ceil(progress)<20&&$(".ui-label",this).is(":visible"))labelEl.hide();else if(labelEl.is(":hidden"))labelEl.fadeIn();if(Math.ceil(progress)==100){labelEl.text("Done");setTimeout(function(){labelEl.fadeOut()},1E3)}else valueEl.text(Math.ceil(progress)+"%")},
complete:function(scope,i,elem){if(callback)callback.call(this,i,elem)}})})}})(jQuery);function isset(){var a=arguments,l=a.length,i=0,undef;if(l===0)throw new Error("Empty isset");while(i!==l){if(a[i]===undef||a[i]===null)return false;i++}return true};